name: Exploring varoables and secrets

on: 
    push

env:
        CONTAINER_REGISTRY: docker.io
        IMAGE_NAME: github-actions-nginx


# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Docker build
#       run: docker build -t docker.io/dockerUsername/imageName:latest
    
#     - name: Docker login
#       run: docker login --username=dockerUsename --passworc=Snen2ejb
    
#     - name: Docker publish
#       run: docker push docker.io/dockerUsename/imageName:latest

#   deploy:
#     needs: docker
#     runs-on: ubuntu-latest
#     steps:
#     - name: Docker run
#       run: docker run -d -p 8080:80 docker.io/dockerUsename/imageName:latest



## --------------------------------------environment variables at step leveL---------------------------------------------- ##
# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Docker build
#       env:
#         CONTAINER_REGISTRY: docker.io
#         DOCKER_USERNAME: srikanth
#         IMAGE_NAME: github-actions-nginx
#       run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    
#     - name: Docker login
#       env:
#         CONTAINER_REGISTRY: docker.io
#         DOCKER_USERNAME: srikanth
#         IMAGE_NAME: github-actions-nginx
#       run: echo docker login --username=dockerUsename --passworc=Snen2ejb
    
#     - name: Docker login
#       env:
#         CONTAINER_REGISTRY: docker.io
#         DOCKER_USERNAME: srikanth
#         IMAGE_NAME: github-actions-nginx
#       run: echo docker push docker.io/dockerUsename/imageName:latest
  
#   deploy:
#     needs: docker
#     runs-on: ubuntu-latest
#     steps:
#     - name: Docker run
#       env:
#         CONTAINER_REGISTRY: docker.io
#         DOCKER_USERNAME: srikanth
#         IMAGE_NAME: github-actions-nginx
#       run: echo docker run -d -p 8080:80 docker.io/dockerUsename/imageName:latest

## ---------------------environment variables at job leveL-If they are repeating at step level-------------------------- ##

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     env:
#         CONTAINER_REGISTRY: docker.io
#         DOCKER_USERNAME: srikanth
#         IMAGE_NAME: github-actions-nginx
#     steps:
#     - name: Docker build
#       run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    
#     - name: Docker login
#       run: echo docker login --username=dockerUsename --passworc=Snen2ejb
    
#     - name: Docker push
#       run: echo docker push docker.io/dockerUsename/imageName:latest
  
#   deploy:
#     needs: docker
#     runs-on: ubuntu-latest
#     steps:
#     - name: Docker run
#       env:
#         CONTAINER_REGISTRY: docker.io
#         DOCKER_USERNAME: srikanth
#         IMAGE_NAME: github-actions-nginx
#       run: echo docker run -d -p 8080:80 docker.io/dockerUsename/imageName:latest

## ---------------------environment variables at job leveL-If they are repeating at job level-------------------------- ##  

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Docker build
      run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    
    - name: Docker login
      run: echo docker login --username=dockerUsename --password=${{  secrets.DOCKER_PASSWORD }}
    
    - name: Docker push
      run: echo docker push docker.io/dockerUsename/imageName:latest
  
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Docker run
      run: echo docker run -d -p 8080:80 docker.io/dockerUsename/imageName:latest
 